package br.com.itau.teste.melhorcerveja.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.*;

import javax.validation.constraints.*;

@Getter
@Setter
@ToString
@NoArgsConstructor
@DynamoDBTable(tableName = "Cervejas")
public class Cerveja {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String id;

    @NotEmpty(message = "Nome é obrigatório!")
    @DynamoDBAttribute
    private String nome;

    @PositiveOrZero(message = "Pontuação deve ser maior ou igual a 0")
    @DynamoDBAttribute
    private Long pontuacao = 0L;

    public Cerveja(String nome) {
        this.nome = nome;
    }

    public void votar() {
        this.pontuacao++;
    }
}
